image:
  file: .gitpod.Dockerfile
  context: apache
# This is to get rid of the annoying popup feel free to leave this out
ports:
  - port: 8080
    onOpen: open-preview
tasks:
- name: Terminal
  command: >
    echo "";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log